authentication/urls.py
from django.contrib import admin
from django.urls import path, include


from . import views

app_name = "authentication"

urlpatterns = [
    path('', views.login_view, name='login_view'),
    path('sign_up_user/', views.sign_up_user, name='sign_up_user'),
    path('signup_page/', views.signup_view, name='signup_view'),
    path('log_in_user/', views.log_in_user, name='log_in_user'),
    path('logout/', views.logout_user, name='logout_user'),


]

blog/urls.py
from django.urls import path, include
from . import views

app_name = "blog"

urlpatterns = [

    path('login/', include('authentication.urls')),

    path('', views.blog_posts_list_view, name='blog_view'),
    path('post/<int:pk>/', views.blog_post_view, name='blog_post_view'),
    path('create_post_view/', views.create_post_view, name='create_post_view'),
    path('publish_post/', views.publish_post, name='publish_post'),
    path('delete_post/', views.delete_post, name='delete_post'),
    path('edit_post/<int:pk>/', views.edit_post_view, name='edit_post'),
    path('projects', views.projects_list_view, name='projects_list_view'),
    path('create_project_view/', views.create_project_view, name='create_project_view'),
    path('publish_project/', views.publish_project, name='publish_project'),
    path('project/<int:pk>/', views.project_view, name='project_view'),
    path('delete_project/', views.delete_project, name='delete_project'),
    path('edit_project/<int:pk>/', views.edit_project_view, name='edit_project'),
    path('about_me', views.about_me_view, name='about_me_view'),
]

authentication/models.py
from django.db import models

# Create your models here.

authentication/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.shortcuts import render, redirect, reverse


def login_view(request):
    return render(request, 'login.html')


def log_in_user(request):
    if request.method == 'POST':
        print(request)
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            # authentication successful, log in the user
            login(request, user)
            # Redirect the user to a different page
            return render(request, 'blogPosts/blog_posts_list_view.html')
        else:
            # authentication failed, display an error message
            return render(request, 'blogPosts/blog_posts_list_view.html', {'error_message': 'Invalid username or password'})
    else:
        # Handle GET requests, such as displaying the login form
        return render(request, 'blogPosts/blog_posts_list_view.html')


def sign_up_user(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        userName = request.POST.get('username')
        try:
            user = User.objects.get(username=userName)
            return render(request, 'login.html', {'error_message': 'User already exists'})
        except User.DoesNotExist:
            password = request.POST.get('password')
            firstName = request.POST.get('firstname')
            lastName = request.POST.get('lastname')

            user = User.objects.create_user(userName, email, password)
            user.first_name = firstName
            user.last_name = lastName
            user.save()

        return render(request, 'login.html')

    else:
        # Handle GET requests or other methods
        return HttpResponse("This view only accepts POST requests")


def signup_view(request):
    return render(request, 'signup_page.html')


def logout_user(request):
    logout(request)
    return redirect('/')

authentication/templates/login.html
<!DOCTYPE html>
{% extends "base.html" %}
{% block content %}

<html lang="en">
<head>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/log_in.css' %}">
    <meta charset="UTF-8">
    <title>About Us</title>
</head>
<body>

    <div class="formDiv">
        <form method="post" action="{% url 'authentication:log_in_user' %}">
            {% csrf_token %}
            <h3>Login Here</h3>

            <label for="username">Username</label>
            <input type="text" placeholder="Email or Phone" id="username" name="username">

            <label for="password">Password</label>
            <input type="password" placeholder="Password" id="password" name="password">

            <button>Log In</button>
            <a href="{% url 'authentication:signup_view' %}">Sign Up</a>
        </form>
    </div>
</body>
{% endblock %}
</html>

authentication/templates/signup_page.html
<!DOCTYPE html>
{% extends "base.html" %}
{% block content %}

<html lang="en">
<head>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/sign_up_page.css' %}">
    <meta charset="UTF-8">
    <title>About Us</title>
</head>
<body>

    <div class="formDiv">
        <form method="post" action="{% url 'authentication:sign_up_user' %}">
            {% csrf_token %}
            <h3>Sign up</h3>

            <label for="username">Username</label>
            <input type="text" placeholder="Username" id="username" name="username">

            <label for="password">Password</label>
            <input type="password" placeholder="Password" id="password" name="password">

            <label for="password">Repeat password</label>
            <input type="password" placeholder="Password" id="password" name="password">

            <label for="username">E-mail</label>
            <input type="text" placeholder="Email" id="email" name="email">

            <label for="username">First name (Optional)</label>
            <input type="text" placeholder="First name" id="firstname" name="firstname">

            <label for="username">Last name (Optional)</label>
            <input type="text" placeholder="Last name" id="lastname" name="lastname">

            <button>Sign up</button>

        </form>
    </div>
</body>
{% endblock %}
</html>