authentication/urls.py
from django.contrib import admin
from django.urls import path, include


from . import views

app_name = "authentication"

urlpatterns = [
    path('', views.login_view, name='login_view'),
    path('sign_up_user/', views.sign_up_user, name='sign_up_user'),
    path('signup_page/', views.signup_view, name='signup_view'),
    path('log_in_user/', views.log_in_user, name='log_in_user'),
    path('logout/', views.logout_user, name='logout_user'),


]

blog/urls.py
from django.urls import path, include
from . import views

app_name = "blog"

urlpatterns = [

    path('login/', include('authentication.urls')),

    path('', views.blog_posts_list_view, name='blog_view'),
    path('post/<int:pk>/', views.blog_post_view, name='blog_post_view'),
    path('create_post_view/', views.create_post_view, name='create_post_view'),
    path('publish_post/', views.publish_post, name='publish_post'),
    path('delete_post/', views.delete_post, name='delete_post'),
    path('edit_post/<int:pk>/', views.edit_post_view, name='edit_post'),
    path('projects', views.projects_list_view, name='projects_list_view'),
    path('create_project_view/', views.create_project_view, name='create_project_view'),
    path('publish_project/', views.publish_project, name='publish_project'),
    path('project/<int:pk>/', views.project_view, name='project_view'),
    path('delete_project/', views.delete_project, name='delete_project'),
    path('edit_project/<int:pk>/', views.edit_project_view, name='edit_project'),
    path('about_me', views.about_me_view, name='about_me_view'),
]

templates/base.html
<!DOCTYPE html>
<html>
<head>
    <title>
        {% block title %}
        {% endblock %}
    </title>
    {% load django_bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/blog.css' %}">
</head>
<body>


     <header>
        <a href="{% url 'blog_view' %}" class="blogLink">
            <img src="{% static 'images/profile_cat.jpg' %}" class="header_image" usemap="#homeLinkMap">
        </a>

        <div class="flexDiv">
             <div class="linkDiv" id="linkDiv">

                 <a href="{% url 'blog_view' %}" class="blogLink"><h5><b>Blog</b></h5></a>
                 <a href="{% url 'projects_list_view' %}" class="blogLink"><h5><b>Projects</b></h5></a>
                 <a href="{% url 'about_me_view' %}" class="aboutMeLink"><h5><b>About me</b></h5></a>
                 {% if request.user.is_authenticated %}
                    <a href="{% url 'authentication:logout_user' %}" class="logoutLink"><h5><b>Log out</b></h5></a>
                 {% endif %}

             </div>
         </div>
     </header>

    <div class="main_body">
        <main>
            {% block content %}
            {% endblock %}
        </main>
    </div>

    <footer>
        <ul class="linkList">
          <li><a href="https://www.linkedin.com/in/robert-gustafsson-bba35b1ba/" class="iconLink" id="linkedinLink">
              <h1><img src="{% static 'images/linkedin.svg' %}" class="icons" id="linkedinIcon" width="40" height="40">
              </h1></a>
          </li>

          <li><a href="https://github.com/carrotunderscore" class="iconLink" id="githubLink">
              <h1><img src="{% static 'images/github.svg' %}" class="icons" id="githubIcon" width="40" height="40">
              </h1></a>
          </li>

            <li><a href="https://www.instagram.com/carrotunderscore/" class="iconLink" id="catApiLink">
                <h1><img src="{% static 'images/instagram.svg' %}" class="icons" id="instagramIcon" width="40" height="40">
                </h1></a>
            </li>
        </ul>

    </footer>

</body>
</html>